[workspace]
members = [
    "circuits/plonk",
    "circuits/kimchi",
    "curves",
    "dlog",
    "dlog/commitment",
    "dlog/plonk",
    "dlog/kimchi",
    "groupmap",
    "ocaml/ocaml-gen",
    "ocaml/ocaml-gen/derive",
    "oracle",
    "signer",
    "utils",
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
