[workspace]
members = [
    "cairo",
    "crypto",
    "curves",
    "groupmap",
    "kimchi",
    "ocaml/ocaml-gen",
    "ocaml/ocaml-gen/derive",
    "oracle",
    "poly-commitment",
    "utils",
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
