[package]
name = "mina-curves"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ark-ec = { version = "0.3.0", features = ["parallel"] }
ark-ff = { version = "0.3.0", features = ["parallel", "asm"] }
ark-serialize = "0.3.0"
serde = "1.0.130"
serde_with = "1.10.0"

[dev-dependencies]
rand = { version = "0.8.0", default-features = false }
ark-algebra-test-templates = "0.3.0"
ark-std = "0.3.0"
