[package]
name = "mina-hasher"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[dependencies]
oracle = { path = "../oracle" }
mina-curves = { path = "../curves" }
o1-utils = { path = "../utils" }

ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }

bitvec = "1.0.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}
lazy_static = "1"
lockfree-object-pool = "0.1"
serde_json = { version = "1.0" }

[profile.bench]
lto = true

[[bench]]
harness = false
name = "bench_hasher_pooling"
path = "tests/bench_hasher_pooling.rs"
