[book]
authors = ["Izaak Meckler", "Vanishree Rao", "Matthew Ryan", "Joseph Spadavecchia", "David Wong", "Vitaly Zelov"]
language = "en"
multilingual = false
src = "src"
title = "Mina book"

[output.html]
site-url = "/proof-systems/"
curly-quotes = true
git-repository-url = "https://www.github.com/o1-labs/proof-systems"

# for LaTeX
[preprocessor.katex]
