name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  # https://doc.rust-lang.org/cargo/reference/profiles.html#release
  RUSTFLAGS: -Coverflow-checks=y -Cdebug-assertions=y
  # https://doc.rust-lang.org/cargo/reference/profiles.html#incremental
  CARGO_INCREMENTAL: 1

jobs:
  run_checks:
    runs-on: ubuntu-latest
    name: Run some basic checks and tests
    steps:
      #
      # Setup
      #

      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up cargo/rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.58.0"
          components: rustfmt, clippy

      - name: Cache Rust stuff
        uses: Swatinem/rust-cache@v1

      - name: Setup OCaml (because of ocaml-gen)
        run: |
          sudo apt update
          sudo apt install -y ocaml

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      #
      # Tests
      # 

      - name: Test with latest nextest release (faster than cargo test)
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all-features --profile ci

      #
      # Coding guidelines
      #

      - name: Enforce formating
        run: cargo fmt -- --check

      # TODO: Need clippy for `--features ocaml_types`?
      - name: Enforce clean clippy output
        run: cargo clippy -- -D warnings

      #
      # Doc & Spec
      #

      - name: Set up cargo-spec for specifications
        run: |
          cargo install cargo-spec --version 0.4.1

      - name: Build the kimchi specification
        run: |
          cd book/specifications
          cd kimchi && make build

      - name: Build the polynomial commitment specification
        run: |
          cd book/specifications
          cd poly-commitment && make build

      - name: Check that up-to-date specification is checked in
        run: |
          git diff --exit-code
