name: Basic rust CI stuff

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_checks:
    runs-on: ubuntu-latest
    name: Run some basic checks
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up cargo/rust
        run: |
          rustup component add rustfmt

      - name: Setup OCaml (because of ocaml-gen)
        run: sudo apt update && sudo apt install ocaml

      - name: build
        run: |
          cargo build

      - name: build ocaml types
        run: |
          cargo build --features ocaml_types

      - name: Run cargo fmt
        run: |
          cargo fmt -- --check

      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings

      - name: Check that up-to-date specification is checked in
        run: |
          cargo install cargo-spec --version 0.1.3
          cd book/specifications
          cd kimchi && make build && cd ..
          cd poly-commitment && make build && cd ..
          git diff --exit-code
